export const dataBase = [
  {
    id: 1,
    name: "CloudSpace Study Hub",
    location: "Malate",
    locType: "Study Hub and Coffee Shop",
    star: 4.7,
    availableSeats: 20,
    image: "/images/1.jpg",
    googleMaps:
      "https://www.google.com/maps/search/Cloudscape+Study+Hub/@14.5643921,120.9946749,15z?entry=s&sa=X&ved=1t%3A199789",
    operatingHours: "10am - 9pm",
    peakTime: "6pm - 7pm",
    price: "100-500 php",
    amenities: [
      "Free Wifi",
      "Quiet Zones",
      "Food Options Available",
      "Printing Services",
      "Parking Space",
    ],
  },
  {
    id: 2,
    name: "Drip Kofi",
    location: "Malate",
    locType: "Cafe",
    star: 4.3,
    availableSeats: 25,
    image: "/images/2.jpg",
    googleMaps: "https://maps.app.goo.gl/yfdnTFjCWeiAx7jq5",
    operatingHours: "8am - 12am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available", "Parking Space"],
  },
  {
    id: 3,
    name: "U ME KAPE",
    location: "Malate",
    locType: "Cafe",
    star: 4.6,
    availableSeats: 18,
    image: "/images/3.jpg",
    googleMaps: "https://maps.app.goo.gl/AtiE5qbbVBvoSJHd8",
    operatingHours: "8am - 2am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available", "Quiet Zones"],
  },
  {
    id: 4,
    name: "Obscure Cafe",
    location: "Malate",
    locType: "Cafe",
    star: 4.5,
    availableSeats: 22,
    image: "/images/4.jpg",
    googleMaps: "https://maps.app.goo.gl/1jyWP1eLggLhXXec6",
    operatingHours: "10am - 1am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available", "Parking Space"],
  },
  {
    id: 5,
    name: "Coffee Project co-lab",
    location: "Malate",
    locType: "Cafe",
    star: 4.4,
    availableSeats: 20,
    image: "/images/5.jpg",
    googleMaps: "https://maps.app.goo.gl/H2KWgCJ1o2C9Vge58",
    operatingHours: "7am - 12:30am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: [
      "Free Wifi",
      "Food Options Available",
      "Conference Rooms",
      "Parking Space",
    ],
  },
  {
    id: 6,
    name: "Candid Coffee",
    location: "Ermita",
    locType: "Cafe",
    star: 4.8,
    availableSeats: 16,
    image: "/images/6.jpg",
    googleMaps: "https://maps.app.goo.gl/oubfXTQCMTt6eA9c7",
    operatingHours: "8am - 9pm",
    peakTime: "5pm - 8pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Quiet Zones", "Food Options Available"],
  },
  {
    id: 7,
    name: "COFFEEPAGES",
    location: "Ermita",
    locType: "Cafe",
    star: 4.3,
    availableSeats: 18,
    image: "/images/7.jpg",
    googleMaps: "https://maps.app.goo.gl/EgaqMCxH8Ex6h3uf9",
    operatingHours: "6am - 11pm",
    peakTime: "4pm - 6pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available", "Printing Services"],
  },
  {
    id: 8,
    name: "ARK Cafe",
    location: "Ermita",
    locType: "Cafe",
    star: 4.7,
    availableSeats: 15,
    image: "/images/8.jpg",
    googleMaps: "https://maps.app.goo.gl/efqw9BRFC1VbbykQA",
    operatingHours: "8am - 8:30pm",
    peakTime: "3pm - 6pm",
    price: "100-200 php",
    amenities: ["Free Wifi", "Food Options Available"],
  },
  {
    id: 9,
    name: "Study Corner",
    location: "Ermita",
    locType: "Study Hub",
    star: 4.8,
    availableSeats: 30,
    image: "/images/9.jpg",
    googleMaps: "https://maps.app.goo.gl/QMe55surkKLXvRdR6",
    operatingHours: "8am - 8pm",
    peakTime: "5pm - 8pm",
    price: "200-400 php",
    amenities: [
      "Free Wifi",
      "Quiet Zones",
      "Printing Services",
      "Conference Rooms",
    ],
  },
  {
    id: 10,
    name: "Obscure Cafe",
    location: "Ermita",
    locType: "Cafe",
    star: 4.5,
    availableSeats: 25,
    image: "/images/10.jpg",
    googleMaps: "https://maps.app.goo.gl/mcbVm3U1kgb4MW4u9",
    operatingHours: "10am - 1am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available", "Parking Space"],
  },
  {
    id: 11,
    name: "HomeRoom Co-Working and Study Lounge",
    location: "Sampaloc",
    locType: "Study Hub",
    star: 4.9,
    availableSeats: 40,
    image: "/images/11.jpg",
    googleMaps: "https://maps.app.goo.gl/KNUoYMJzHdD34WbY8",
    operatingHours: "12pm - 6am",
    peakTime: "9pm - 12am",
    price: "200-400 php",
    amenities: ["Free Wifi", "Quiet Zones", "Printing Services", "Open 24/7"],
  },
  {
    id: 12,
    name: "933 Coworking Cafe",
    location: "Sampaloc",
    locType: "Study Hub and Coffee Shop",
    star: 4.9,
    availableSeats: 25,
    image: "/images/12.jpg",
    googleMaps: "https://maps.app.goo.gl/8AsUUQMUdi8F3Air7",
    operatingHours: "8am - 5am",
    peakTime: "9pm - 12am",
    price: "200-400 php",
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Open 24/7",
      "Food Options Available",
    ],
  },
  {
    id: 13,
    name: "Sumu Creative Space",
    location: "Sampaloc",
    locType: "Study Hub and Coffee Shop",
    star: 4.1,
    availableSeats: 20,
    image: "/images/13.jpg",
    googleMaps: "https://maps.app.goo.gl/NGHyfgZSJqACZyf18",
    operatingHours: "6am - 3am",
    peakTime: "6pm - 11pm",
    price: "200-400 php",
    amenities: [
      "Free Wifi",
      "Food Options Available",
      "Quiet Zones",
      "Open 24/7",
    ],
  },
  {
    id: 14,
    name: "Goodside Coffee",
    location: "Sampaloc",
    locType: "Cafe",
    star: 4.9,
    availableSeats: 18,
    image: "/images/14.jpg",
    googleMaps: "https://maps.app.goo.gl/2fzXUWxbMP46WkiXA",
    operatingHours: "10:30am - 12am",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Free Coffee", "Food Options Available"],
  },
  {
    id: 15,
    name: "Calle Cafe",
    location: "Sampaloc",
    locType: "Cafe",
    star: 4.1,
    availableSeats: 15,
    image: "/images/15.jpg",
    googleMaps: "https://maps.app.goo.gl/TkPvWfWnFN7iW82x6",
    operatingHours: "9am - 11pm",
    peakTime: "6pm - 9pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available"],
  },
  {
    id: 16,
    name: "Cafe Y Ruedas",
    location: "Intramuros",
    locType: "Cafe",
    star: 4.6,
    availableSeats: 20,
    image: "/images/16.jpg",
    googleMaps: "https://maps.app.goo.gl/S7VW2eUuMcb6NqFC9",
    operatingHours: "10am - 10pm",
    peakTime: "3pm - 6pm",
    price: "100-500 php",
    amenities: ["Free Wifi", "Food Options Available", "Parking Space"],
  },
  {
    id: 17,
    name: "Cafe Intramuros",
    location: "Intramuros",
    locType: "Cafe",
    star: 3.7,
    availableSeats: 15,
    image: "/images/17.jpg",
    googleMaps: "https://maps.app.goo.gl/BSQf777DAMgTwg5w7",
    operatingHours: "10:30am - 8pm",
    peakTime: "6pm - 7pm",
    price: "200-400 php",
    amenities: ["Free Wifi", "Food Options Available"],
  },
  {
    id: 18,
    name: "La Cathedral Cafe",
    location: "Intramuros",
    locType: "Cafe",
    star: 3.7,
    availableSeats: 20,
    image: "/images/18.jpg",
    googleMaps: "https://maps.app.goo.gl/16uqv1LFEaAVdRHVA",
    operatingHours: "8am - 9pm",
    peakTime: "6pm - 9pm",
    price: "100-200 php",
    amenities: ["Free Wifi", "Food Options Available", "Quiet Zones"],
  },
  {
    id: 19,
    name: "IN Cafe Bar",
    location: "Intramuros",
    locType: "Study Hub and Coffee Shop",
    star: 4.5,
    availableSeats: 18,
    image: "/images/19.jpg",
    googleMaps: "https://maps.app.goo.gl/tf2X8JbyzdqgwYL97",
    operatingHours: "9am - 9pm",
    peakTime: "1pm - 7pm",
    price: "200-400 php",
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Quiet Zones",
      "Food Options Available",
    ],
  },
];
