// Student Cafes Database
export const dataBase = [
  {
    id: 1,
    name: "The Study Brew",
    location: "Makati City",
    locType: "Cafe",
    star: 4.2,
    availableSeats: 15,
    image: "/images/1.jfif",
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Food Options Available",
      "Open 24/7",
    ],
  },
  {
    id: 2,
    name: "Campus Corner Cafe",
    location: "Quezon City",
    locType: "Lounge",
    star: 3.8,
    availableSeats: 11,
    image: "/images/1.jfif",
    amenities: [
      "Free Wifi",
      "Food Options Available",
      "Parking Space",
      "Printing Services",
    ],
  },
  {
    id: 3,
    name: "The Green Lounge",
    location: "Taguig City",
    locType: "Co-Working",
    star: 4.5,
    image: "/images/1.jfif",
    amenities: ["Free Wifi", "Quiet Zones", "Printing Services", "Open 24/7"],
  },
  {
    id: 4,
    name: "Tech Hub Cafe",
    location: "Pasig City",
    locType: "Cafe",
    star: 4.1,
    image: "/images/1.jfif",
    amenities: ["Free Wifi", "Free Coffee", "Quiet Zones", "Conference Rooms"],
  },
  {
    id: 5,
    name: "Sunset Terrace Cafe",
    location: "Parañaque City",
    locType: "Cafe",
    star: 4.8,
    image: "/images/1.jfif",
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Food Options Available",
      "Quiet Zones",
      "Conference Rooms",
      "Parking Space",
      "Printing Services",
      "Open 24/7",
    ],
  },
  {
    id: 6,
    name: "Manila Bay Study Hub",
    location: "City of Manila",
    locType: "Co-Working",
    star: 4.3,
    image: "/images/1.jfif",
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Printing Services",
      "Food Options Available",
    ],
  },
  {
    id: 7,
    name: "Quiet Corner Lounge",
    location: "Las Piñas City",
    locType: "Lounge",
    star: 3.9,
    amenities: ["Free Wifi", "Quiet Zones", "Free Coffee", "Parking Space"],
  },
  {
    id: 8,
    name: "Urban Grind Cafe",
    location: "Pasay City",
    locType: "Cafe",
    star: 4.0,
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Food Options Available",
      "Open 24/7",
    ],
  },
  {
    id: 9,
    name: "BGC Study Space",
    location: "Taguig City",
    locType: "Co-Working",
    star: 4.7,
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Quiet Zones",
      "Printing Services",
      "Parking Space",
    ],
  },
  {
    id: 10,
    name: "Caloocan Coffee House",
    location: "Caloocan",
    locType: "Cafe",
    star: 3.6,
    amenities: ["Free Wifi", "Free Coffee", "Food Options Available"],
  },
  {
    id: 11,
    name: "Shaw Study Center",
    location: "Mandaluyong",
    locType: "Co-Working",
    star: 4.4,
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Quiet Zones",
      "Printing Services",
      "Open 24/7",
    ],
  },
  {
    id: 12,
    name: "Alabang Lounge",
    location: "Muntinlupa",
    locType: "Lounge",
    star: 4.2,
    amenities: [
      "Free Wifi",
      "Food Options Available",
      "Parking Space",
      "Free Coffee",
    ],
  },
  {
    id: 13,
    name: "Eastwood Study Hub",
    location: "Quezon City",
    locType: "Co-Working",
    star: 4.6,
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Printing Services",
      "Quiet Zones",
      "Food Options Available",
    ],
  },
  {
    id: 14,
    name: "Ortigas Workspace",
    location: "Pasig City",
    locType: "Co-Working",
    star: 4.5,
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Parking Space",
      "Printing Services",
      "Open 24/7",
    ],
  },
  {
    id: 15,
    name: "Makati Coffee Co.",
    location: "Makati City",
    locType: "Cafe",
    star: 4.3,
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Food Options Available",
      "Quiet Zones",
    ],
  },
  {
    id: 16,
    name: "Intramuros Study Nook",
    location: "City of Manila",
    locType: "Lounge",
    star: 3.7,
    amenities: ["Free Wifi", "Quiet Zones", "Food Options Available"],
  },
  {
    id: 17,
    name: "Las Piñas Co-Work",
    location: "Las Piñas City",
    locType: "Co-Working",
    star: 4.0,
    amenities: [
      "Free Wifi",
      "Conference Rooms",
      "Parking Space",
      "Printing Services",
    ],
  },
  {
    id: 18,
    name: "Airport Road Cafe",
    location: "Parañaque City",
    locType: "Cafe",
    star: 3.8,
    amenities: ["Free Wifi", "Free Coffee", "Open 24/7", "Parking Space"],
  },
  {
    id: 19,
    name: "Bay Area Lounge",
    location: "Pasay City",
    locType: "Lounge",
    star: 4.1,
    amenities: [
      "Free Wifi",
      "Food Options Available",
      "Quiet Zones",
      "Parking Space",
    ],
  },
  {
    id: 20,
    name: "Fort Bonifacio Cafe",
    location: "Taguig City",
    locType: "Cafe",
    star: 4.6,
    amenities: [
      "Free Wifi",
      "Free Coffee",
      "Food Options Available",
      "Quiet Zones",
      "Conference Rooms",
    ],
  },
];

export const locations = [
  "Makati City",
  "City of Manila",
  "Quezon City",
  "Las Piñas City",
  "Parañaque City",
  "Pasay City",
  "Taguig City",
  "Pasig City",
  "Caloocan",
  "Mandaluyong",
  "Muntinlupa",
];

export const amenities = [
  "Free Wifi",
  "Free Coffee",
  "Food Options Available",
  "Quiet Zones",
  "Conference Rooms",
  "Parking Space",
  "Printing Services",
  "Open 24/7",
];
